import type { Metadata } from 'next';
import { Building2, Lock, Wallet } from 'lucide-react';
import { listProviders, isProviderImplemented } from '@/lib/ai/registry';
import { decrypt, maskSecret } from '@/lib/crypto';
import type { ModelProviderId } from '@/lib/ai/types';
import { Card, CardBody, CardHeader, CardTitle } from '@/components/ui/card';
import { ModelConnections, type ConnectionRecord } from '@/components/settings/model-connections';
import { UsagePanel, type UsageRow } from '@/components/settings/usage-panel';
import type { ProviderInfo } from '@/components/settings/provider-info';
import { query, type SearchParamsInput } from '../../_lib/data';

export const metadata: Metadata = { title: 'Model Connections' };

type ConnectionRow = {
  id: string;
  label: string;
  provider: ModelProviderId;
  model: string;
  base_url: string | null;
  encrypted_api_key: string | null;
  input_cost_per_mtok: number | null;
  output_cost_per_mtok: number | null;
  max_output_tokens: number;
  is_default: boolean;
  enabled: boolean;
  last_checked_at: string | null;
  last_check_ok: boolean | null;
  last_check_error: string | null;
};

type UsageQueryRow = {
  feature: string;
  calls: number | string;
  input_tokens: number | string;
  output_tokens: number | string;
  cost_usd: number | string;
  failures: number | string;
};

/**
 * The stored value is ciphertext, so masking it directly would show the user a
 * meaningless slice of base64. Decrypting on the server and masking the result
 * gives them enough of the key to recognize which one is configured, and the
 * plaintext never crosses back to a browser.
 */
function maskStored(ciphertext: string | null): string | null {
  if (!ciphertext) return null;
  try {
    return maskSecret(decrypt(ciphertext));
  } catch {
    return '•••••••• (unreadable — check ENCRYPTION_KEY)';
  }
}

const PILLARS = [
  {
    icon: Lock,
    title: 'Nothing leaves for a vendor you did not pick',
    body: 'Briefs and answers are generated by the endpoint configured here and no other. Newsroom copy, embargoed reporting and competitive analysis all stay inside the boundary your organization already accepted.',
  },
  {
    icon: Wallet,
    title: 'The spend is yours, at cost',
    body: 'Inference bills to your own provider account at your own negotiated rate. There is no per-seat AI surcharge and no markup, and the usage panel below reconciles against the invoice you already receive.',
  },
  {
    icon: Building2,
    title: 'Switch on the day a better model ships',
    body: 'The model field is free text on purpose. When something better lands on a Tuesday you change one string, not a contract. When something gets deprecated, you are not waiting on a vendor roadmap.',
  },
];

export default async function ModelSettingsPage({
  searchParams,
}: {
  searchParams: Promise<SearchParamsInput>;
}) {
  await searchParams;
  const { requireOrg } = await import('@/lib/session');
  const { orgId } = await requireOrg();

  const providerDefs = listProviders();
  const providers: ProviderInfo[] = providerDefs.map((p) => ({
    id: p.id,
    displayName: p.displayName,
    baseUrl: p.baseUrl,
    needsApiKey: p.needsApiKey,
    keyUrl: p.keyUrl,
    suggestedModels: p.suggestedModels,
    implemented: isProviderImplemented(p.id),
  }));
  const providerLabels = new Map(providers.map((p) => [p.id, p.displayName]));

  const monthStart = new Date();
  monthStart.setDate(1);
  monthStart.setHours(0, 0, 0, 0);

  const [connections, usage] = await Promise.all([
    query<ConnectionRow>(({ sql }) => sql`
      SELECT id, label, provider, model, base_url, encrypted_api_key,
             input_cost_per_mtok, output_cost_per_mtok, max_output_tokens,
             is_default, enabled, last_checked_at, last_check_ok, last_check_error
        FROM model_connections
       WHERE org_id = ${orgId}::uuid
       ORDER BY is_default DESC, created_at ASC
    `),
    query<UsageQueryRow>(({ sql }) => sql`
      SELECT feature,
             count(*) AS calls,
             coalesce(sum(input_tokens), 0) AS input_tokens,
             coalesce(sum(output_tokens), 0) AS output_tokens,
             coalesce(sum(cost_usd), 0) AS cost_usd,
             count(*) FILTER (WHERE ok = false) AS failures
        FROM ai_usage
       WHERE org_id = ${orgId}::uuid
         AND created_at >= ${monthStart.toISOString()}
       GROUP BY feature
       ORDER BY sum(cost_usd) DESC
    `),
  ]);

  const records: ConnectionRecord[] = connections.data.map((c) => ({
    id: c.id,
    label: c.label,
    provider: c.provider,
    providerLabel: providerLabels.get(c.provider) ?? c.provider,
    model: c.model,
    baseUrl: c.base_url,
    maskedKey: maskStored(c.encrypted_api_key),
    inputCostPerMtok: c.input_cost_per_mtok,
    outputCostPerMtok: c.output_cost_per_mtok,
    maxOutputTokens: c.max_output_tokens,
    isDefault: c.is_default,
    enabled: c.enabled,
    lastCheckedAt: c.last_checked_at,
    lastCheckOk: c.last_check_ok,
    lastCheckError: c.last_check_error,
  }));

  const usageRows: UsageRow[] = usage.data.map((u) => ({
    feature: u.feature,
    calls: Number(u.calls) || 0,
    inputTokens: Number(u.input_tokens) || 0,
    outputTokens: Number(u.output_tokens) || 0,
    costUsd: Number(u.cost_usd) || 0,
    failures: Number(u.failures) || 0,
  }));

  const monthLabel = new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(monthStart);

  return (
    <div className="mx-auto max-w-5xl space-y-4">
      <Card>
        <CardHeader>
          <div className="min-w-0">
            <CardTitle className="text-base">Bring your own model</CardTitle>
            <p className="mt-1 max-w-3xl text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
              Pressbox does not ship a hosted model, and it does not resell anyone else’s. It calls
              the inference your organization already controls. For a newsroom that is not a
              preference — it is the difference between a tool you can put reporting into and one you
              cannot.
            </p>
          </div>
        </CardHeader>
        <CardBody>
          <ul className="grid gap-4 sm:grid-cols-3">
            {PILLARS.map((p) => (
              <li key={p.title}>
                <span className="inline-flex h-7 w-7 items-center justify-center rounded-md border border-zinc-200 bg-zinc-50 dark:border-zinc-800 dark:bg-zinc-900">
                  <p.icon className="h-3.5 w-3.5 text-accent-600" strokeWidth={1.75} aria-hidden />
                </span>
                <h3 className="mt-2 text-xs font-semibold text-zinc-900 dark:text-zinc-100">{p.title}</h3>
                <p className="mt-1 text-[11px] leading-relaxed text-zinc-500 dark:text-zinc-400">{p.body}</p>
              </li>
            ))}
          </ul>
        </CardBody>
      </Card>

      {connections.error ? (
        <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-400">
          {'Connections could not be read: ' + connections.error}
        </p>
      ) : null}

      <ModelConnections connections={records} providers={providers} />

      <UsagePanel rows={usageRows} monthLabel={monthLabel} />
    </div>
  );
}
