'use client';

import * as React from 'react';
import { Cpu, Hand } from 'lucide-react';
import { cn } from '@/lib/utils';
import { InfoTip } from '@/components/ui/tooltip';
import { MetricDefinition } from '@/components/ui/metric-label';
import type { MetricKey } from '@/lib/types';

/**
 * The two-kind vocabulary, made visible.
 *
 * A reader of this screen has to be able to tell at a glance which numbers the
 * machine stands behind and which numbers a person typed. That distinction is
 * the entire product, so it is a permanent, unmissable label on every section
 * rather than a note in the documentation.
 */
export type SectionKind = 'computed' | 'manual';

export function KindBadge({ kind }: { kind: SectionKind }) {
  const computed = kind === 'computed';
  const Icon = computed ? Cpu : Hand;
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider',
        computed
          ? 'bg-accent-600/10 text-accent-700 dark:bg-accent-600/15 dark:text-accent-400'
          : 'bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400',
      )}
      title={
        computed
          ? 'Derived from ingested data. Read-only, and regenerated by recompute.'
          : 'Pasted from a system this app does not read. Entered by hand.'
      }
    >
      <Icon className="h-2.5 w-2.5" aria-hidden />
      {computed ? 'Computed' : 'Manual'}
    </span>
  );
}

export function SectionCard({
  title,
  kind,
  description,
  actions,
  footer,
  children,
}: {
  title: string;
  kind: SectionKind;
  description?: React.ReactNode;
  actions?: React.ReactNode;
  footer?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-lg border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900/40">
      <header className="flex flex-wrap items-start justify-between gap-3 border-b border-zinc-200 px-4 py-3 dark:border-zinc-800">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="text-sm font-semibold tracking-tight text-zinc-900 dark:text-zinc-100">
              {title}
            </h3>
            <KindBadge kind={kind} />
          </div>
          {description ? (
            <p className="mt-1 max-w-2xl text-xs leading-relaxed text-zinc-500 dark:text-zinc-400">
              {description}
            </p>
          ) : null}
        </div>
        {actions ? <div className="flex shrink-0 items-center gap-2">{actions}</div> : null}
      </header>
      {children}
      {footer ? (
        <footer className="border-t border-zinc-200 px-4 py-2 text-[11px] text-zinc-500 dark:border-zinc-800">
          {footer}
        </footer>
      ) : null}
    </section>
  );
}

/**
 * A labelled figure whose label always carries its definition.
 *
 * `metric` uses the app-wide metric dictionary so the definition here and the
 * definition on the cross-channel screen cannot drift; `hint` is for the few
 * report-only figures the dictionary does not cover.
 */
export function Figure({
  label,
  metric,
  hint,
  value,
  sub,
  tone = 'neutral',
}: {
  label: string;
  metric?: MetricKey;
  hint?: React.ReactNode;
  value: string;
  sub?: React.ReactNode;
  tone?: 'neutral' | 'up' | 'down';
}) {
  const definition = metric ? <MetricDefinition metric={metric} /> : hint;
  return (
    <div className="min-w-0">
      <div className="flex items-center gap-1.5 text-[11px] font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
        <span className="truncate">{label}</span>
        {definition ? <InfoTip content={definition} label={label} side="bottom" align="start" /> : null}
      </div>
      <p
        className={cn(
          'pb-num mt-1 text-lg font-semibold tracking-tight',
          tone === 'up' && 'text-emerald-700 dark:text-emerald-400',
          tone === 'down' && 'text-red-700 dark:text-red-400',
          tone === 'neutral' && 'text-zinc-900 dark:text-zinc-50',
        )}
      >
        {value}
      </p>
      {sub ? <p className="pb-num mt-0.5 text-[11px] text-zinc-500 dark:text-zinc-400">{sub}</p> : null}
    </div>
  );
}

/** Column header that carries a definition, for the read-only computed tables. */
export function HeaderWithDefinition({
  label,
  metric,
  hint,
}: {
  label: string;
  metric?: MetricKey;
  hint?: React.ReactNode;
}) {
  const definition = metric ? <MetricDefinition metric={metric} /> : hint;
  return (
    <span className="inline-flex items-center gap-1">
      <span>{label}</span>
      {definition ? <InfoTip content={definition} label={label} side="bottom" align="end" /> : null}
    </span>
  );
}
