import * as React from 'react';
import Link from 'next/link';
import type { V2Data } from '@/lib/v2/reader';
import { PLATFORM_LABELS } from '@/lib/types';
import { metricText, neighborId, observedCounter, safeWebUrl, timestamp } from '@/lib/v2/presentation';
import { transitionUrl } from '@/lib/v2/state';
import { PostMedia } from './media';
import { InspectorKeyboard } from './keyboard';
export function Inspector({ data }: { data: V2Data }) {
  const { detail: post, state, posts } = data;
  const ids = posts?.items.map(p => p.id) ?? [];
  const previous = neighborId(ids, state.post, -1), next = neighborId(ids, state.post, 1);
  if (!post) return <aside className="v2-inspector v2-inspector-empty" aria-label="Post inspector"><p className="v2-eyebrow">Post inspector</p><h2>{state.post ? 'Post unavailable in this scope' : 'Select a post'}</h2><p>{state.post ? 'The post may be outside these filters or no longer accessible. Select a visible post to continue.' : 'Inspect the original post, captured performance and available comments without leaving the list.'}</p></aside>;
  const permalink = safeWebUrl(post.permalink);
  return <aside className="v2-inspector" aria-label="Post inspector"><InspectorKeyboard />
    <header className="v2-inspector-header"><span className="v2-eyebrow">Post inspector</span><Link href={transitionUrl('/v2/posts', state, { post: '', inspect: 'post' })} scroll={false} aria-label="Close post inspector">Close ×</Link></header>
    <div className="v2-inspector-nav">{previous ? <Link id="v2-previous-post" href={transitionUrl('/v2/posts', state, { post: previous })} scroll={false}>← Previous post</Link> : <span aria-disabled="true">← Previous post</span>}{next ? <Link id="v2-next-post" href={transitionUrl('/v2/posts', state, { post: next })} scroll={false}>Next post →</Link> : <span aria-disabled="true">Next post →</span>}</div>
    <p className="v2-note">Arrow keys navigate posts on this results page when not typing.</p>
    <div className="v2-inspector-identity"><h2>{post.company.name}</h2><p>{PLATFORM_LABELS[post.platform]} · @{post.channel.handle} · {post.type}</p><time dateTime={post.postedAt}>{timestamp(post.postedAt)}</time></div>
    <nav className="v2-tabs" aria-label="Post inspection sections">{(['post','performance','comments'] as const).map(inspect => <Link key={inspect} href={transitionUrl('/v2/posts', state, { inspect })} scroll={false} aria-current={state.inspect === inspect ? 'page' : undefined}>{inspect.charAt(0).toUpperCase()+inspect.slice(1)}</Link>)}</nav>
    <div className="v2-inspector-content">
      {state.inspect === 'post' && <><PostMedia key={post.id} url={post.thumbnailUrl} company={post.company.name} postId={post.id} landscape={state.landscape} archived={post.hasArchivedThumbnail} large /><p className="v2-full-post">{post.text || 'No captured post text.'}</p>{post.tags.length > 0 && <div className="v2-tag-list" aria-label="Captured tags">{post.tags.map(t => <span key={t.id}>{t.name}</span>)}</div>}{post.urls.length > 0 && <section><h3>Linked pages</h3><ul className="v2-linked-pages">{post.urls.map(u => <li key={u.url}>{safeWebUrl(u.url) ? <a href={u.url} target="_blank" rel="noopener noreferrer">{u.title || u.domain || u.url} ↗</a> : <span>Link unavailable</span>}</li>)}</ul></section>}</>}
      {state.inspect === 'performance' && <><h3>Latest stored performance</h3><dl className="v2-key-values">{([['Engagements', observedCounter(post.engagementTotal)], ['Applause', observedCounter(post.applause)], ['Comments / replies', observedCounter(post.conversation)], ['Shares / reposts', observedCounter(post.amplification)], ['Views', observedCounter(post.views)], ['Follower engagement rate', metricText('engagementRateByFollower', post.engagementRateByFollower, !!post.followersAtPost && post.followersAtPost > 0 && post.engagementTotal > 0)]] as const).map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="v2-note">Cumulative observations, not reactions earned in the publication window. The post read does not certify individual counter availability; stored zeros are withheld (—), not presented as measured zero.</p><h3>Capture history</h3>{post.metricHistory.length ? <div className="v2-table-scroll"><table className="v2-table"><caption>Up to 50 most recent stored captures</caption><thead><tr><th scope="col">Captured</th><th scope="col" className="v2-number">Engagements</th></tr></thead><tbody>{post.metricHistory.map((h,i) => <tr key={h.capturedAt+i}><td>{timestamp(h.capturedAt)}</td><td className="v2-number">{observedCounter(h.engagementTotal)}</td></tr>)}</tbody></table></div> : <p className="v2-muted">No metric snapshots captured for this post.</p>}</>}
      {state.inspect === 'comments' && <><h3>Captured comments</h3><p>{metricText('posts', post.comments.collected)} stored · {post.comments.items.length} shown</p><p className="v2-note">The source-captured, most-liked sample for this post; not a representative sample of its audience. Text may be truncated. No sentiment or AI summary is inferred.</p>{post.comments.items.length ? <ol className="v2-comments">{post.comments.items.map(c => <li key={c.id}><p>{c.text || 'No captured text.'}</p><span>{metricText('posts',c.likes)} likes · {metricText('posts',c.replies)} replies{c.commentedAt ? ' · '+timestamp(c.commentedAt) : ''}</span></li>)}</ol> : <div className="v2-empty"><h3>No comment text captured</h3><p>This does not mean nobody commented. Collection varies by platform and source.</p></div>}</>}
    </div><footer className="v2-inspector-footer">{permalink ? <a className="v2-button" href={permalink} target="_blank" rel="noopener noreferrer">Open original post ↗</a> : <p>Original post link unavailable.</p>}<p className="v2-note">Last stored refresh: {timestamp(post.lastRefreshedAt)}<br />First observed: {timestamp(post.firstSeenAt)}</p></footer>
  </aside>;
}
