/**
 * The week in sentences.
 *
 * Every screen in this product answered "here is everything we measured" and
 * none of them answered "what happened". A senior person opening the landing
 * page had to do the analysis themselves, in their head, in a meeting — and a
 * tool that makes its most valuable readers work is a tool they stop opening.
 *
 * This turns numbers already on the page into three plain findings. Nothing
 * here is generated by a model: these are deterministic readings of the same
 * leaderboard and post rows the charts below them render, so a headline can
 * never disagree with the evidence under it. Every claim also carries the
 * figure behind it, because a sentence a reader cannot check is a sentence a
 * reader should not trust.
 *
 * The honesty rules from CONTRACTS.md hold: incomplete rows are excluded from
 * ranking claims rather than ranked as if measured, and a finding that cannot
 * be supported is simply not produced. Three findings is the target, zero is a
 * legitimate outcome on a thin window.
 */
import type { MetricRow } from '@/lib/types';
import type { PostDto } from './contract';

export interface Headline {
  /** Short label for the finding, e.g. "Standing". */
  kind: 'standing' | 'breakout' | 'story' | 'volume';
  /** The sentence, already written. */
  text: string;
  /** The figure that supports it, rendered beside the sentence. */
  figure?: string;
  /** Where clicking the finding should go, when there is a natural target. */
  href?: string;
}

export interface WeekHeadlineInput {
  focusCompanyId: string | null;
  focusName: string;
  /** Leaderboard rows for engagementTotal, any order. */
  engagement: MetricRow[];
  /** Channel-balanced top posts for the landscape in this window. */
  topPosts: PostDto[];
  /** Days in the selected window, for phrasing. */
  days: number;
  /** Carried onto finding links so a click keeps the viewer's scope. */
  scopeQuery?: string;
}

const ORDINALS = ['0th', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'];

function ordinal(n: number): string {
  if (n < ORDINALS.length) return ORDINALS[n];
  const rem100 = n % 100;
  if (rem100 >= 11 && rem100 <= 13) return `${n}th`;
  switch (n % 10) {
    case 1: return `${n}st`;
    case 2: return `${n}nd`;
    case 3: return `${n}rd`;
    default: return `${n}th`;
  }
}

function compact(value: number): string {
  const abs = Math.abs(value);
  if (abs >= 1_000_000) return `${(value / 1_000_000).toFixed(abs >= 10_000_000 ? 0 : 1)}M`;
  if (abs >= 1_000) return `${(value / 1_000).toFixed(abs >= 10_000 ? 0 : 1)}k`;
  return String(Math.round(value));
}

function firstWords(text: string, words: number): string {
  const clean = text.replace(/\s+/g, ' ').trim();
  if (!clean) return '';
  const parts = clean.split(' ');
  if (parts.length <= words) return clean;
  return `${parts.slice(0, words).join(' ')}…`;
}

/**
 * Where the focus brand sits on engagement, among brands actually measured.
 *
 * Rows without complete coverage are excluded from the field rather than
 * ranked, because a brand that was only half-collected has not earned a
 * position. When the focus brand itself is incomplete, no standing is claimed.
 */
function standing(input: WeekHeadlineInput): Headline | null {
  const { focusCompanyId, focusName, engagement } = input;
  if (!focusCompanyId) return null;
  const ranked = engagement
    .filter((row) => row.available && row.complete !== false && Number.isFinite(row.value))
    .sort((a, b) => b.value - a.value);
  if (ranked.length < 3) return null;
  const index = ranked.findIndex((row) => row.company.id === focusCompanyId);
  if (index < 0) return null;

  const place = index + 1;
  const total = ranked.length;
  const value = ranked[index].value;
  const leader = ranked[0];

  const text = place === 1
    ? `${focusName} leads the market on engagement, ahead of ${ranked[1].company.name}.`
    : `${focusName} ranks ${ordinal(place)} of ${total} on engagement. ${leader.company.name} leads.`;

  return { kind: 'standing', text, figure: `${compact(value)} engagement` };
}

/**
 * The single post that most outperformed its own publisher's norm.
 *
 * Raw engagement would just name whoever has the largest following every week.
 * The outlier multiple asks a better question: who made something that beat
 * their own typical reach, which is the part another newsroom can learn from.
 */
function breakout(input: WeekHeadlineInput): Headline | null {
  const candidates = input.topPosts
    .filter((post) => typeof post.outlierScore === 'number'
      && Number.isFinite(post.outlierScore)
      && post.outlierScore >= 3
      && post.engagementTotal > 0);
  if (candidates.length === 0) return null;
  const best = candidates.reduce((a, b) => ((b.outlierScore ?? 0) > (a.outlierScore ?? 0) ? b : a));
  const multiple = Math.round(best.outlierScore ?? 0);
  const snippet = firstWords(best.text ?? '', 12);
  const subject = snippet ? `“${snippet}”` : 'a single post';

  return {
    kind: 'breakout',
    text: `${best.company.name} had the week's breakout: ${subject}`,
    figure: `${multiple}× their normal, ${compact(best.engagementTotal)} engagement`,
    href: best.permalink ?? undefined,
  };
}

/**
 * What the market was collectively about, by tag weight across top posts.
 *
 * Counting tagged posts alone would reward whoever posts most; weighting by
 * the engagement those posts earned answers the question an editor is actually
 * asking, which is what the audience showed up for.
 */
function story(input: WeekHeadlineInput): Headline | null {
  const weights = new Map<string, { name: string; id: string; engagement: number; posts: number }>();
  for (const post of input.topPosts) {
    for (const tag of post.tags) {
      const current = weights.get(tag.id)
        ?? { name: tag.name, id: tag.id, engagement: 0, posts: 0 };
      current.engagement += post.engagementTotal;
      current.posts += 1;
      weights.set(tag.id, current);
    }
  }
  if (weights.size === 0) return null;
  const top = [...weights.values()].sort((a, b) => b.engagement - a.engagement)[0];
  // One post carrying a tag is an anecdote, not the week's story.
  if (top.posts < 2) return null;

  const scope = input.scopeQuery ? `&${input.scopeQuery}` : '';
  return {
    kind: 'story',
    text: `The market's biggest story was ${top.name}, across ${top.posts} of the top posts.`,
    figure: `${compact(top.engagement)} engagement`,
    href: `/posts?tags=${top.id}${scope}`,
  };
}

/** Up to three findings, strongest first, or none when the window is too thin. */
export function buildWeekHeadlines(input: WeekHeadlineInput): Headline[] {
  return [standing(input), breakout(input), story(input)]
    .filter((finding): finding is Headline => finding !== null);
}
